departmentapp/urls.py
from django.urls import path, include
from . import views

app_name = 'departmentapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('<dept_code>/',views.dashboard, name='dashboard'),
    path('<dept_code>/academic',views.academic,name='academic'),
    path('<dept_code>/academic/add', views.add_academic, name='add_academic'),
    path('<dept_code>/academic/filter', views.filter_academic, name='filter_academic'),
    path('<dept_code>/academic/<staff_id>', views.academic_profile, name='academic_profile'),
    path('<dept_code>/academic/<staff_id>/edit', views.edit_academic, name='edit_academic'),
    path('<dept_code>/nonacademic', views.nonacademic, name='nonacademic'),
    path('<dept_code>/nonacademic/add', views.add_nonacademic, name='add_nonacademic'),
    path('<dept_code>/nonacademic/filter', views.filter_nonacademic, name='filter_nonacademic'),
    path('<dept_code>/nonacademic/<staff_id>', views.nonacademic_profile, name='nonacademic_profile'),
    path('<dept_code>/nonacademic/<staff_id>/edit', views.edit_nonacademic, name='edit_nonacademic'),
    path('<dept_code>/course', views.course, name='course'),
    path('<dept_code>/course/add', views.add_course, name='add_course'),
    path('<dept_code>/course/filter', views.filter_course, name='filter_course'),
    path('<dept_code>/course/<course_code>', views.course_profile, name='course_profile'),
    path('<dept_code>/course/<course_code>/edit', views.edit_course, name='edit_course'),
    path('<dept_code>/ajax/addinstruct/<course_code>', views.add_instruct, name='add_instruct'),
    path('<dept_code>/ajax/deletestaff/<staff_id>', views.delete_employee, name='delete_employee'),
    path('<dept_code>/ajax/deletecourse/<course_code>', views.delete_course, name='delete_course'),
    path('<dept_code>/ajax/<course_code>/removeinstructor', views.remove_instructor, name='remove_instructor'),
    path('test', views.test, name='test'),
]

departmentdb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('departmentapp/',include('departmentapp.urls')),
]

departmentapp/models.py
from django.db import models

# Create your models here.

departmentapp/views.py
from django.shortcuts import render, redirect
from django.db import connection,transaction
from django.conf import settings
from django.utils.datastructures import MultiValueDictKeyError
import os
from . import tables


# Create your views here.


def home(request):
    result = tables.department.getall()
    print(result)
    return render(request,'departmentapp/home.html',{'result':result})

def dashboard(request,dept_code):
    result = tables.department.get("dept_code = '{}'".format(dept_code))
    if not result['error']:
        # try catch block check if empty record is returned through indexing operation
        try:
            #   To get the department details
            result = {'error': False, 'department': result['rows'][0]}

            #   To get the course count of the department
            course_count = tables.course.count("department_id = {}".format(result['department']['dept_id']))
            if(course_count['error']):
                raise Exception('Course Count Error')
            result['course_count'] = course_count['value']

            #   To get the academic staff count of the department
            academic_count = tables.count(tables.join('academic','employee'),'*','department_id = {}'.format(result['department']['dept_id']))
            if(academic_count['error']):
                raise Exception('Academic Staff Count Error')
            result['academic_count'] = academic_count['value']

            #   To get the nonacademic staff count of the department
            nonacademic_count = tables.count(tables.join('nonacademic', 'employee'), '*',
                                          'department_id = {}'.format(result['department']['dept_id']))
            if (nonacademic_count['error']):
                raise Exception('Non-Academic Staff Count Error')
            result['nonacademic_count'] = nonacademic_count['value']

            #   To get the HOD details in a dictionary field 'hod'
            hod_details = tables.get(tables.join('employee','academic'),'salutation,staff_id,staff_fname,staff_lname,email,mobile_contact,photo_url',
                                     condition='department_id = {} and post_id = {}'.format(result['department']['dept_id'],1))
            if(hod_details['error'] or hod_details['rows'] == [] ):
                raise Exception('HOD Details cannot be retrieved')
            result['hod'] = hod_details['rows'][0]  # Since, only one HOD in each dept, index 0 will only be filled in result

            #   To get the Deputy HOD details in a dictionary field 'dhod'
            dhod_details = tables.get(tables.join('employee', 'academic'),
                                     'salutation,staff_id,staff_fname,staff_lname,email,mobile_contact,photo_url',
                                     condition='department_id = {} and post_id = {}'.format(
                                         result['department']['dept_id'], 2))
            if (dhod_details['error'] or dhod_details['rows'] == []):
                raise Exception('Deputy HOD Details cannot be retrieved')
            result['dhod'] = dhod_details['rows']  # Since, more than one HOD is possible in a dept, no indexing


        except IndexError as e:
            result = {'error': True, 'message': 'No such department is enlisted in the database'}

        except Exception as e:
            result = {'error': True, 'department': result['department'], 'message': 'There was an error in querying the database: {}'.format(str(e))}

    return render(request,'departmentapp/dashboard.html',{'result':result})

def academic(request,dept_code):
    result = tables.department.get("dept_code = '{}'".format(dept_code))
    if not result['error']:
        # try catch block check if empty record is returned through indexing operation
        try:
            #   To get the department details
            result = {'error': False, 'department': result['rows'][0]}

            #   To get the entire list of academic staffs in that department
            column_names = 'staff_id,salutation,staff_fname,staff_mname,staff_lname,email,mobile_contact,designation'
            staff_list = tables.get('academicsummary',column_names,'department_id = {}'.format(result['department']['dept_id']),order='staff_fname')
            if staff_list['error']:
                raise Exception('Academic Staff retrieval error')
            result['staff_list'] = staff_list['rows']

            #   To get the post list for filtering
            post_list = tables.academic_post.getall()
            if not post_list['error']:
                result['postlist'] = post_list['rows']

        except IndexError as e:
            result = {'error': True, 'message': 'No such department is enlisted in the database'}

        except Exception as e:
            result = {'error': True, 'department': result['department'],
                      'message': 'There was an error in querying the database: {}'.format(str(e))}

    return render(request, 'departmentapp/academic.html', {'result': result})


def filter_academic(request,dept_code):
    print('AJAX filter request received')
    formdata = dict(request.POST.copy())
    result = tables.department.get("dept_code = '{}'".format(dept_code))

    if not result['error']:
        try:
            #   To get the department details
            result = {'error': False, 'department': result['rows'][0]}
            formdata['department_id'] = [result['department']['dept_id']]
            #   To get the filtered list of academic staffs in that department
            column_names = 'staff_id,salutation,staff_fname,staff_mname,staff_lname,email,mobile_contact,designation'
            print('Filter Form Data: {}'.format(formdata))
            filter_columns = [field for field in formdata if field!='csrfmiddlewaretoken']
            filter_values = [formdata[field][0] for field in formdata if field!='csrfmiddlewaretoken']

            staff_list = tables.filter('academicsummary',filter_columns,filter_values,order='staff_fname')
            if staff_list['error']:
                raise Exception('No academic staffs were found with the specified criterias')
            result['staff_list'] = staff_list['rows']

        except IndexError as e:
            result = {'error': True, 'message': 'No such department is enlisted in the database'}

        except Exception as e:
            result = {'filtererror': True, 'department': result['department'],
                      'message': 'There was an error in querying the database: {}'.format(str(e))}

    return render(request, 'departmentapp/academictable.html', {'result': result})


def nonacademic(request,dept_code):
    result = tables.department.get("dept_code = '{}'".format(dept_code))
    if not result['error']:
        # try catch block check if empty record is returned through indexing operation
        try:
            #   To get the department details
            result = {'error': False, 'department': result['rows'][0]}

            #   To get the entire list of non-academic staffs in that department
            column_names = 'staff_id,staff_fname,staff_mname,staff_lname,email,mobile_contact,post_name'
            staff_list = tables.get(tables.join(tables.join('nonacademic', 'employee'),'nonacademic_post','left',
                                                on='nonacademic.post_id=nonacademic_post.post_id'), column_names,
                                    'department_id = {}'.format(result['department']['dept_id']),order='staff_fname')
            if staff_list['error']:
                raise Exception('Non-Academic Staff retrieval error')
            result['staff_list'] = staff_list['rows']

            #   To get the post list for filtering
            post_list = tables.nonacademic_post.getall()
            if not post_list['error']:
                result['postlist'] = post_list['rows']

        except IndexError as e:
            result = {'error': True, 'message': 'No such department is enlisted in the database'}

        except Exception as e:
            result = {'error': True, 'department': result['department'],
                      'message': 'There was an error in querying the database: {}'.format(str(e))}

    return render(request, 'departmentapp/nonacademic.html', {'result': result})


def filter_nonacademic(request,dept_code):
    print('AJAX filter request received')
    formdata = dict(request.POST.copy())
    result = tables.department.get("dept_code = '{}'".format(dept_code))

    if not result['error']:
        try:
            #   To get the department details
            result = {'error': False, 'department': result['rows'][0]}
            formdata['department_id'] = [result['department']['dept_id']]
            #   To get the filtered list of academic staffs in that department
            print('Filter Form Data: {}'.format(formdata))
            filter_columns = [field for field in formdata if field!='csrfmiddlewaretoken']
            filter_values = [formdata[field][0] for field in formdata if field!='csrfmiddlewaretoken']

            staff_list = tables.filter('nonacademicsummary',filter_columns,filter_values,order='staff_fname')
            if staff_list['error']:
                raise Exception('No non-academic staffs were found with the specified criterias')
            result['staff_list'] = staff_list['rows']

        except IndexError as e:
            result = {'error': True, 'message': 'No such department is enlisted in the database'}

        except Exception as e:
            result = {'filtererror': True, 'department': result['department'],
                      'message': 'There was an error in querying the database: {}'.format(str(e))}

    return render(request, 'departmentapp/nonacademictable.html', {'result': result})


def course(request,dept_code):
    result = tables.department.get("dept_code = '{}'".format(dept_code))
    if not result['error']:

departmentapp/templates/departmentapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

   <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Department Faculty and Staff Database</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/sidebar.css' %}" rel="stylesheet">

    <style>
    .modal-backdrop {
        opacity: 0.8;
    }
    </style>
    {% block extracss %}
    {% endblock extracss %}

</head>

<body>


    <div id="wrapper" style="margin: auto;">

        <!-- Sidebar -->
        <div id="sidebar-wrapper" style=" display: block;">
            {% block sidebar %}
            {% endblock %}
        </div>

        <div id="page-wrapper" style="padding: 0 5%;">
            {% block content %}
            {% endblock content %}
        </div>


    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block extrajs %}
    {% endblock %}

</body>

</html>

departmentapp/templates/departmentapp/courseprofile.html
{% extends 'departmentapp/base.html' %}
{% load static %}

{% block sidebar %}
    {% include 'departmentapp/sidebar.html' with dept_code=result.department.dept_code %}
{% endblock %}

{% block content %}
    {% if not result.error %}
    <div class="row">
         <div class="page-header col-lg-12">
            <span style="font-size: 200%">{{ result.course.course_name }} ({{ result.course.course_code }})</span>
            {% if result.course.elective %}
                <span class="label label-info" style="margin-left: 2%; font-size: 100%">
                 Elective
                </span>
            {% endif %}
         </div>
    </div>
    <div class="row">

        <div class="col-lg-4">
            <button class="btn btn-danger " data-toggle="modal" data-target="#deleteCourseModal">
                <span class="fa fa-trash"></span> Delete Course
            </button>
            <a class="btn btn-primary" href="{% url 'departmentapp:edit_course' result.department.dept_code result.course.course_code %}">
                <span class="fa fa-edit"></span> Update Course
            </a>
        </div>

        <div class="col-lg-3 col-lg-push-5">
            <button class="btn btn-success pull-right" data-target="#addInstructorModal" data-toggle="modal">
                    <span class="glyphicon glyphicon-plus-sign"></span> Assign New Instructor
            </button>
        </div>

        <div class="modal" id="addInstructorModal" data-backdrop="static" data-keyboard="false">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="modal-title">
                            <h3>Assign a new instructor for {{ result.course.course_code }}
                                <a class="close" href="{% url 'departmentapp:course_profile' result.department.dept_code result.course.course_code %} ">&times</a></h3>
                        </div>

                    </div>
                    <div class="modal-body" id="assignInstructorBody">
                        {% include 'departmentapp/addinstructform.html' with result=result %}
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>

        <div class="modal" id="deleteCourseModal" data-backdrop="static" data-keyboard="false">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="modal-title">
                            <h3><span id="courseDeletionTitle"> Are you sure you want to delete this course?</span>
                                <a id="courseModalCloseBtn" class="close" href="{% url 'departmentapp:course_profile' result.department.dept_code result.course.course_code %} ">&times</a></h3>
                        </div>

                    </div>
                    <div class="modal-body" id="deleteCourseBody">
                        <p>
                            Deleting the record of this course will completely erase every relevant records associated with it. Proceed with caution!
                        </p>
                        <button class="btn btn-danger" id="delete-course" data-href="{% url 'departmentapp:delete_course' result.department.dept_code result.course.course_code %}">
                            Proceed
                        </button>
                        <button class="btn btn-primary" data-dismiss="modal">Cancel</button>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row" >
        <div class="col-lg-8 col-lg-offset-2" style="margin-top: 0%">
            <div id="instructs-table-wrapper" class="row">
                <hr>
                <h4>Academic staffs currently teaching this course:</h4>
                <hr>
                {% if not result.current_stafflist|length == 0 %}
                <table width="100%" class="table table-striped table-bordered table-hover" id="teacher-table">
                    <thead>
                        <tr>
                            <th>Program</th>
                            <th>Semester</th>
                            <th>Staff Name</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for staff in result.current_stafflist %}
                            <tr>
                                <td>{{ staff.program }}</td>
                                <td>{{ staff.semester }}</td>
                                <td>{{ staff.staff_fname }} {{ staff.staff_mname }} {{ staff.staff_lname }}</td>
                                <td class="text-center">
                                    <button class="staff-removal btn btn-sm btn-danger" data-program="{{ staff.program }}"
                                            data-semester="{{ staff.semester }}" data-staff="{{ staff.staff_id }}">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="modal" id="removeInstModal" data-backdrop="static" data-keyboard="false">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <div class="modal-title">
                                    <h3><span id="deletionTitle"> Are you sure you want to remove this instructor?</span>
                                        <a id="modalCloseBtn" class="close" href="{% url 'departmentapp:course_profile' result.department.dept_code result.course.course_code %} ">&times</a></h3>
                                </div>

                            </div>
                            <div class="modal-body" id="removeInstBody">
                                <p>
                                    Removing this instructor means he/she will no longer be assigned to teach the course. Proceed with caution!
                                </p>
                                <button class="btn btn-danger" id="remove-instructor" >
                                    Proceed
                                </button>
                                <button class="btn btn-primary" data-dismiss="modal">Cancel</button>
                            </div>
                            <div class="modal-footer">
                            </div>
                        </div>
                    </div>
                </div>
                {% else %}
                    <div class="row alert alert-info">
                        No staff has been assigned to teach this course!
                    </div>
                {% endif %}
            </div>
            <p></p>
            <div id="canteach-table-wrapper" class="row">
                <hr>
                <h4>Academic staffs who can teach this course:</h4>
                <hr>
                {% if not result.capable_stafflist|length == 0 %}
                <table width="100%" class="table table-striped table-bordered table-hover" id="teacher-table">
                    <thead>
                        <tr>
                            <th>Staff ID</th>
                            <th>Staff Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for staff in result.capable_stafflist %}
                            <tr>
                                <td>{{ staff.staff_id }}</td>
                                <td>{{ staff.staff_fname }} {{ staff.staff_mname }} {{ staff.staff_lname }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                    <div class="row alert alert-info">
                        No staff can teach this course!
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% else %}
        <div class="alert alert-danger">
            <h3>ERROR</h3>
            <p>{{ result.message }}</p>
        </div>
    {% endif %}

{% endblock %}

{% block extrajs %}
    <script>
        var refreshEvent = new Event('refresh');
        var instructBody = document.querySelector('#assignInstructorBody');
        var modalToggleBtns = document.querySelectorAll('.staff-removal');
        var deleteBtn = document.querySelector('#remove-instructor');
        var deleteBody = document.querySelector('#removeInstBody');
        var modalTitle = document.querySelector('#deletionTitle');
        var deletecourseBtn = document.querySelector('#delete-course');
        var deletecourseBody = document.querySelector('#deleteCourseBody');
        var selectedStaffID = null;
        var selectedStaffSemester = null;
        var selectedStaffProgram = null;

        instructBody.addEventListener('refresh',function (ev) {
            var instructForm = document.querySelector('#assignInstructorForm');
            instructForm.addEventListener('submit',function (event) {
                var formdata = new FormData(instructForm);
                var submitURL = instructForm.getAttribute('data-submit');
                var req = new XMLHttpRequest();
                req.open('POST',submitURL,true);
                req.addEventListener('load',function (ev) {
                    instructBody.innerHTML = this.responseText;
                    instructBody.dispatchEvent(refreshEvent)
                });
                req.send(formdata);
                event.preventDefault();

            });
        });

        deletecourseBtn.addEventListener('click',function (event) {
            var req = new XMLHttpRequest();
            req.open('GET',this.getAttribute('data-href'),true);
            req.addEventListener('load',function (ev) {
                deletecourseBody.innerHTML = this.responseText;
                var title = document.querySelector('#courseDeletionTitle');
                var backlink = document.querySelector('#courseModalCloseBtn');
                title.textContent = 'Deletion Details';
                backlink.setAttribute('href',"{% url 'departmentapp:course' result.department.dept_code %}");
            });
            req.send();
        });

        modalToggleBtns.forEach(function (modalToggleBtn) {
            modalToggleBtn.addEventListener('click',function (e) {
                selectedStaffID = this.getAttribute('data-staff');
                selectedStaffSemester = this.getAttribute('data-semester');
                selectedStaffProgram = this.getAttribute('data-program');
                console.log('Selected staff ID: '+selectedStaffID);
                console.log('Selected staff semester: '+selectedStaffSemester);
                console.log('Selected staff program: '+selectedStaffProgram);
                $('#removeInstModal').modal();
            })
        });

        if (deleteBtn != null){     // When there are no remove buttons due to no current teaching staff
            deleteBtn.addEventListener('click',function (event) {
                var req = new XMLHttpRequest();
                req.open('GET',"{% url 'departmentapp:remove_instructor' result.department.dept_code result.course.course_code %}",true);
                req.setRequestHeader('staffID',selectedStaffID);
                req.setRequestHeader('staffSemester',selectedStaffSemester);
                req.setRequestHeader('staffProgram',selectedStaffProgram);
                req.addEventListener('load',function (ev) {
                    deleteBody.innerHTML = this.responseText;
                    modalTitle.textContent = 'Deletion Details';
                });
                req.send();
            });
        }

        instructBody.dispatchEvent(refreshEvent);

    </script>
{% endblock %}

departmentapp/templates/departmentapp/nonacademic.html
{% extends 'departmentapp/base.html' %}
{% load static %}

{% block extracss %}
    <style>
        #filter-wrapper{
            margin-top: 2%;
        }
    </style>
{% endblock %}

{% block sidebar %}
    {% include 'departmentapp/sidebar.html' with dept_code=result.department.dept_code %}
{% endblock %}

{% block content %}
    {% if not result.error %}
    <div class="row">
         <div class="page-header col-lg-12">
             <a href="{% url 'departmentapp:add_nonacademic' result.department.dept_code %}" class="btn btn-success pull-right" >
                <span class="glyphicon glyphicon-plus-sign"></span> Add Non-Academic Staff
             </a>
             <a href="#" id="exportbtn" class="btn btn-primary pull-right" data-name="Non-Academic Staffs" style="margin-right: 2%">
                <span class="glyphicon glyphicon-export"></span> Export to Excel
            </a>
             <h3>Non Academic Staff</h3>
         </div>
    </div>
    <div class="row">
        <div class="col-lg-12" id="filter-wrapper">
            <form id="filter-form" class="form" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-lg-2">
                        <label for="staff_id">ID:</label>
                        <input type="number" class="form-control" id="staff_id" name="staff_id" >
                    </div>

                    <div class="col-lg-2">
                        <label for="staff_fname">First Name:</label>
                        <input type="text" class="form-control" id="staff_fname" name="staff_fname" >
                    </div>

                    <div class="col-lg-2">
                        <label for="staff_lname">Last Name:</label>
                        <input type="text" class="form-control" id="staff_lname" name="staff_lname" >
                    </div>

                    <div class="col-lg-2">
                        <label for="post_id">Post</label>
                        <select name="post_id" id = "post_id" class="form-control">
                            <option value="" selected></option>
                            {% for post in result.postlist %}
                                <option value="{{ post.post_id }}">{{ post.post_name }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="col-lg-2" style="padding-top: 2%">
                        <span class="input-group-btn">
                            <button class="btn btn-default btn-block" type="submit"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div id="filter-result" class="col-lg-12" style="margin-top: 3%">
            {% include 'departmentapp/nonacademictable.html' with result=result %}
        </div>
    </div>
    {% else %}
        <div class="alert alert-danger">
            <h3>ERROR</h3>
            <p>{{ result.message }}</p>
        </div>
    {% endif %}

{% endblock %}

{% block extrajs %}
    <script>
        var filterForm = document.querySelector('#filter-form');
        var filterResult = document.querySelector('#filter-result');
        var filterEvent = new Event('filter');

        filterResult.addEventListener('filter',function (event) {
            var staffrows = document.querySelectorAll('.staff-row');
            staffrows.forEach(function (row){
                row.addEventListener('mouseenter',function (event) {
                   this.style.backgroundColor = '#34373a';
                   this.style.color = 'white';
                   console.log('MouseEnter: '+this.getAttribute('data-href'));
                });
                row.addEventListener('mouseleave',function (event) {
                   this.style.backgroundColor = 'white';
                   this.style.color = '#333';
                   console.log('MouseLeave: '+this.getAttribute('data-href'));
                });
                row.addEventListener('click',function (event) {
                    window.location = this.getAttribute('data-href');
                    console.log('MouseOver: '+this.getAttribute('data-href'));
                });
            });
        });

        filterForm.addEventListener('submit',function (event) {
            event.preventDefault();
            var formdata = new FormData(this);
            var req = new XMLHttpRequest();
            req.open('POST',"{% url 'departmentapp:filter_nonacademic' result.department.dept_code %}",true);
            req.addEventListener('load',function (ev) {
                filterResult.innerHTML = this.responseText;
                filterResult.dispatchEvent(filterEvent)
            });
            req.send(formdata);
        });

        filterResult.dispatchEvent(filterEvent);
    </script>
    <script src="{% static 'js/excelExporter.js' %}"></script>
{% endblock %}

departmentapp/templates/departmentapp/sidebar.html
{% load static %}
<ul class="sidebar-nav" style="font-size: larger;padding: 15% 0;">
    <div class="row">
        <li class="sidebar-brand">
            <img src="{% static 'images/logo.png' %}" width="40%" height="40%">
            <strong style="color: whitesmoke">{{ dept_code|upper }}</strong>
        </li>
    </div>
    <div class="row">
        <li>
            <a href="{% url 'departmentapp:dashboard' dept_code %}"><span class="fa fa-university"></span> &nbsp; Overview</a>
        </li>
        <li>
            <a href="{% url 'departmentapp:academic' dept_code %}"><span class="fa fa-user"></span> &nbsp; Academic Staff</a>
        </li>
        <li>
            <a href="{% url 'departmentapp:nonacademic' dept_code %}"><span class="fa fa-user"></span> &nbsp; Non Academic Staff</a>
        </li>
        <li>
            <a href="{% url 'departmentapp:course' dept_code %}"><span class="fa fa-book"></span>  &nbsp; Course</a>
        </li>
    </div>
</ul>